### ISSUE TITLE
[BUG] - Image Distortion

### ISSUE THREAD

**Issue by kanjieater** [Snd-R/kurp#2]
I've noticed I get image distortion occasionally (notice the signature blue bit it adds compared to the original), and I think it's Kurp thing, as I can access the image at the default komga url without any distortion. The majority of images are working, but usually about 1 page in any given chapter might do this. It does seem to do it consistently for the image even if I reload after clearing cache
![image](https://github.com/Snd-R/komf/assets/32607317/df5ac8c6-bd62-466b-ad8d-9caed5c29aee)
![image](https://github.com/Snd-R/kurp/assets/32607317/0847760d-714d-4328-9833-3bab871a32b0)

```yml
port: 3030 # listen port
upstream_url: "http://localhost:8443"
upscale: true
size_threshold_enabled: true # enables content size check
size_threshold: 1000 # in KB. will not upscale if image size is bigger than specified size
size_threshold_png: 2000 # in KB. will not upscale if image size is bigger than specified size. PNG only

# return format of the upscaled image. If the original image was png then converting for example to webp
# will result in significantly smaller image size
# available options are "WebP", "Jpeg", "Png" and "Original"
return_format: WebP
upscaler: Realcugan # upscaler to use (Waifu2x or Realcugan)

waifu2x:
  # gpuid: 1 # gpu device to use (-1 = cpu). if you have single gpu then this should usually be 0
  scale: 2 # upscale ratio (1/2/4/8/16/32)
  noise: -1 # denoise level (-1/0/1/2/3)
  model: Cunet # waifu2x model (Cunet, Upconv7AnimeStyleArtRgb, Upconv7Photo)
  tile_size: 0 # tile size (>=32/0=auto)
  tta_mode: false # enable tta mode
  num_threads: 4 #  thread count used for upscaling
  models_path: "./models" # path to directory with models
realcugan:
  gpuid: 0 # gpu device to use (-1 = cpu). if you have single gpu then this should usually be 0
  scale: 2 # upscale ratio (1/2/3/4)
  noise: 0 # denoise level (-1/0/1/2/3)
  model: Se # realcugan model (Se, Pro, Nose)
  tile_size: 0 # tile size (>=32/0=auto)
  sync_gap: 3 # sync gap mode (0/1/2/3)
  tta_mode: false # enable tta mode
  num_threads: 8 #  thread count for upscaling
  models_path: "./models" # path to directory with models
```
